#common configuration shared between all applications
configserver:
    status: ${spring.cloud.config.uri}/${spring.cloud.config.label}/${spring.cloud.config.name}-${spring.cloud.config.profile}.yml/
jhipster:
    security:
        authentication:
            jwt:
                secret: e6c399e1c91efdcd74fdd799858a1d0b3ccbd0c0
