version: '2'
services:
    accountsmicroservice-app:
        image: accountsmicroservice
        external_links:
            - accountsmicroservice-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/accountsmicroservice?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false
    accountsmicroservice-mysql:
        container_name: accountsmicroservice-mysql
        image: mysql:5.7.11
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=accountsmicroservice
        command: mysqld --lower_case_table_names=1 --skip-ssl
    
    accountsmicroservicev2-app:
        image: accountsmicroservicev2
        external_links:
            - accountsmicroservicev2-mysql:mysql
            - accountsmicroservicev2-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/accountsmicroservicev2?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    accountsmicroservicev2-mysql:
        container_name: accountsmicroservicev2-mysql
        image: mysql:5.7.11
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=accountsmicroservicev2
        command: mysqld --lower_case_table_names=1 --skip-ssl
    accountsmicroservicev2-elasticsearch:
        container_name: accountsmicroservicev2-elasticsearch
        image: elasticsearch:1.7.5
    
    hipsterbankgateway-app:
        image: hipsterbankgateway
        external_links:
            - hipsterbankgateway-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hipsterbankgateway?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    hipsterbankgateway-mysql:
        container_name: hipsterbankgateway-mysql
        image: mysql:5.7.11
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=hipsterbankgateway
        command: mysqld --lower_case_table_names=1 --skip-ssl
    
    insurances-app:
        image: insurances
        external_links:
            - insurances-mongodb:mongodb
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=insurances
    insurances-mongodb:
        container_name: insurances-mongodb
        image: mongo:3.2.3
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
