version: '2'
services:
    accountsmicroservicev2-elasticsearch:
        container_name: accountsmicroservicev2-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/accountsMicroservicev2/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
