version: '2'
services:
    accountsmicroservice-app:
        image: accountsmicroservice
        external_links:
            - accountsmicroservice-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/accountsmicroservice?useUnicode=true&characterEncoding=utf8&useSSL=false
    accountsmicroservice-mysql:
        extends:
            file: mysql.yml
            service: accountsmicroservice-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
