version: '2'
services:
    accountsmicroservice-mysql:
        container_name: accountsmicroservice-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/accountsMicroservice/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=accountsmicroservice
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
