version: '2'
services:
    hipsterbankgateway-app:
        image: hipsterbankgateway
        external_links:
            - hipsterbankgateway-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - hipsterbankgateway-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hipsterbankgateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    hipsterbankgateway-mysql:
        extends:
            file: mysql.yml
            service: hipsterbankgateway-mysql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra.yml
        #     service: hipsterbankgateway-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
